version: 1.0.1.{build}
configuration:
    - Debug
    - Release
platform:
    - x64
    - x86
before_build:
    - ps: |
        if ($env:PLATFORM -eq 'x64') {
            cmake . -G "Visual Studio 14 2015 Win64" -DEXAMPLES=Yes
        } else {
            cmake . -G "Visual Studio 14 2015" -DEXAMPLES=Yes
        }
build:
    project: ALL_BUILD.vcxproj
    verbosity: normal
test_script:
    - cmd: test\%CONFIGURATION%\inform_unittest.exe
    - ps: dist\package.ps1
artifacts:
    - path: 'dist\*.zip'
      name: package
deploy:
    description: 'New Release'
    provider: GitHub
    auth_token:
        secure: %GITHUB_TOKEN%
    artifact: dist\*.zip
    draft: true
    prerelease: true
    on:
        branch: master
        APPVEYOR_REPO_TAG: true
