language: c
compiler:
    - gcc
    - clang
os:
    - linux
    - osx
script: cmake . -DEXAMPLES=Yes && make && make test

after_succes:
    - sh dist/package.sh

deploy:
    provider: releases
    api_key:
        secure: $GITHUB_TOKEN
    file: dist/*.tar.gz
    skip_cleanup: true
    on:
        tags: true

