version: 0.0.4.{build}
configuration:
- Debug
- Release
platform:
- x64
- x86
- Any CPU
before_build:
- ps: cmake .
build:
  project: ALL_BUILD.vcxproj
  verbosity: normal
test_script:
- cmd: test\%CONFIGURATION%\inform_unittest.exe
