version: 0.0.3.{build}
configuration:
- Debug
- Release
platform:
- x64
- x86
- Any CPU
before_build:
- ps: cmake .
build:
  project: ALL_BUILD.vcxproj
  verbosity: minimal
test_script:
- cmd: ctest -C %CONFIGURATION%
